### ISSUE TITLE
1.6 is good, but 1.7 gives an error.

### ISSUE THREAD

**Issue by BeOB** [imgk/shadow#8]
![image](https://user-images.githubusercontent.com/46304767/80324186-8c4d2b80-886a-11ea-8e28-75f933fc6819.png)

**Comment by imgk** [comment]
In version 1.7, I changed the default location of `WinDivert64.sys`. You need to put `WinDivert.dll` and `WinDivert64.sys` in `C:\Windows\system32`.

**Comment by BeOB** [comment]
![image](https://user-images.githubusercontent.com/46304767/80324623-b3a4f800-886c-11ea-9c1a-e78194aafc5b.png)

I still get an error.

**Comment by imgk** [comment]
Same error? You can try running `sc stop windivert` to stop the driver. Sometimes a reboot is helpful to solve weird problems.

**Comment by BeOB** [comment]
After rebooting my PC,
I ran the following command(sc stop windivert) but it still gives an error.

**Comment by imgk** [comment]
Can you post the command log history? The problem showed in the first post is that shadowsocks.exe can not find `WinDivert.dll` in the system directory. Putting needed files in the `C:\Windows\system32` should solve that problem.

**Comment by BeOB** [comment]
The log is the same as above.
I am still getting an error.

**Comment by BeOB** [comment]
![image](https://user-images.githubusercontent.com/46304767/80326499-f3231280-8873-11ea-86f9-0214695b80e5.png)
A, B, C all tested.
Both x86 and x64 were tested.
Of course I copied it to the C: \ Windows \ System32 folder.

But,

I still get an error.

**Comment by imgk** [comment]
According to the [explanation](https://pkg.go.dev/golang.org/x/sys/windows?tab=doc#NewLazySystemDLL), `NewLazySystemDLL` will find dlls in the system directory. Mostly, the directory is `C:\Windows\System32`. If go can not find `WinDivert.dll`, The problem might be that your system directory is not `C:\Windows\System32`. Firstly, type `%windir%\System32` in the address bar of file manager to verify whether your system directory is `C:\Windows\System32' or not. If this error still exists, you can modify the source code 
```
winDivert              = windows.NewLazySystemDLL("WinDivert.dll")
```
in `windivert.go`(line 66) to 
```
winDivert              = windows.NewLazyDLL("WinDivert.dll")
```
and put `WinDivert.dll` and `WinDivert64.sys` in the same directory of `shadowsocks.exe`. It works fine for me.

You can download a build version from this [link](https://1drv.ms/u/s!AgkGJqaRN6Q3hN8iJL_zWTQNqg4pSQ?e=XuRm1X),

**Comment by BeOB** [comment]
![image](https://user-images.githubusercontent.com/46304767/80328184-8d398980-8879-11ea-8ef5-54ba9e4d5729.png)
This is good.

**Comment by BeOB** [comment]
I find my system folder.
My system folder is C:\Windows\SysWOW64.
I copied these files(WinDivert.dll, WinDivert64.sys) here.
However, another error occurred.

![image](https://user-images.githubusercontent.com/46304767/80330171-69794200-887f-11ea-9ad5-c22592af81cf.png)

**Comment by imgk** [comment]
It's weird because on Windows 64 bit `C:\Windows\SysWOW64` is the system directory for 32 bit programs while `C:\Windows\System32` is for 64 bit.

It doesn't matter now as I will change `NewLazySystemDLL` to `NewLazyDLL` in the next release. 

I'm not sure about this error as I never have this problem and I can not reproduce it.

If `shadow.exe` works fine on your PC, I'll push the code to github tonight.

**Comment by BeOB** [comment]
Thanks...
